### ISSUE TITLE
Unable to build cargo-audit v0.20.0

### ISSUE THREAD

**Issue by fussybeaver** [rustsec/rustsec#1142]
This came up in the [master build](https://app.circleci.com/pipelines/github/fussybeaver/bollard/1051/workflows/0621a5a3-e1d9-4565-9543-a1d541a3870d/jobs/10293/parallel-runs/0/steps/0-104) for [bollard](https://github.com/fussybeaver/bollard). 

When I build cargo audit on an x86_64 linux machine (or the container for `rust:1.75.0-buster`) using:

```
cargo install cargo-audit
```

I get the following error building rustsec `v0.29.0`:

```
   Compiling rustsec v0.29.0
error[E0433]: failed to resolve: could not find `state` in `worktree`
   --> /home/fussybeaver/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustsec-0.29.0/src/repository/git/commit.rs:146:35
    |
146 |         let opts = gix::worktree::state::checkout::Options {
    |                                   ^^^^^ could not find `state` in `worktree`

error[E0433]: failed to resolve: could not find `state` in `worktree`
   --> /home/fussybeaver/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustsec-0.29.0/src/repository/git/commit.rs:152:24
    |
152 |         gix::worktree::state::checkout(
    |                        ^^^^^ could not find `state` in `worktree`
    |
help: consider importing this crate
    |
3   + use ::gix::worktree::state;
    |
help: if you import `state`, refer to it directly
    |
152 -         gix::worktree::state::checkout(
152 +         state::checkout(
    |

error[E0599]: no method named `fetch_then_checkout` found for struct `tame_index::external::gix::clone::PrepareFetch` in the current scope
   --> /home/fussybeaver/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustsec-0.29.0/src/repository/git/repository.rs:165:22
    |
158 |                   let (mut prep_checkout, out) = gix::prepare_clone(url, path)
    |  ________________________________________________-
159 | |                     .map_err(|err| {
160 | |                         format_err!(ErrorKind::Repo, "failed to prepare clone: {}", err)
161 | |                     })?
...   |
164 | |                     .configure_remote(|remote| Ok(remote.with_refspecs([REF_SPEC], DIR)?))
165 | |                     .fetch_then_checkout(&mut progress, should_interrupt)
    | |                     -^^^^^^^^^^^^^^^^^^^ method not found in `PrepareFetch`
    | |_____________________|
    |

Some errors have detailed explanations: E0433, E0599.
For more information about an error, try `rustc --explain E0433`.
error: could not compile `rustsec` (lib) due to 3 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-audit v0.20.0`, intermediate artifacts can be found at `/tmp/cargo-installOhrhLk`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

**Comment by batleforc** [comment]
Hello,
I have the same issue, not sure if it's a fix that should be used, but I changed the install to `cargo install --locked cargo-audit;`

**Comment by fussybeaver** [comment]
Thanks that seems to work for me.

**Comment by Shnatsel** [comment]
@Byron This seems to be another unintended semver break in `gix`

**Comment by Byron** [comment]
Thanks for letting me know, I am looking into it.
This one seems a little different, and it's definitely more isolated as otherwise the `gitoxide` CI would also have failed by now (among with many others, probably).

**Comment by Byron** [comment]
It's related to `tame-index` - it seems to have upgraded to `gix v0.60`. This project doesn't use its own `gix` version, but uses re-exports of `tame-index` *while* adding features to it. Once `tame-index` changes the version, these features don't apply to the same version anymore, hence the breakage.

To fix this, and I tried it to validate, one can update `Cargo.lock` and use `gix` v0.60 here as well. A quick patch release should fix the installation.

As finally fix, it should be attempted to not use any re-exports of `tame-index`, but instead ones own `gix` dependency. That way, at worst one will compile two different `gix` as `tame-index` might upgrade earlier again.

This kind of dependency chain is definitely something to watch out for, multiple `gix` really doesn't make it easier.

I hope that helps.

**Comment by Shnatsel** [comment]
Should be fixed now

Thank you @Byron for the investigation!

**Comment by jadinm** [comment]
I am still getting the same issue and yet it fetches the version with your fix: rustsec v29.0.1

```
$ cargo install cargo-audit
[...]
   Compiling rustsec v0.29.1
error[E0433]: failed to resolve: could not find `state` in `worktree`
   --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rustsec-0.29.1/src/repository/git/commit.rs:146:35
    |
146 |         let opts = gix::worktree::state::checkout::Options {
    |                                   ^^^^^ could not find `state` in `worktree`

error[E0433]: failed to resolve: could not find `state` in `worktree`
   --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rustsec-0.29.1/src/repository/git/commit.rs:152:24
    |
152 |         gix::worktree::state::checkout(
    |                        ^^^^^ could not find `state` in `worktree`
    |
help: consider importing this crate
    |
3   + use ::gix::worktree::state;
    |
help: if you import `state`, refer to it directly
    |
152 -         gix::worktree::state::checkout(
152 +         state::checkout(
    |

   Compiling is-terminal v0.4.12
   Compiling display-error-chain v0.2.0
error[E0599]: no method named `fetch_then_checkout` found for struct `tame_index::external::gix::clone::PrepareFetch` in the current scope
   --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rustsec-0.29.1/src/repository/git/repository.rs:165:22
    |
158 |                   let (mut prep_checkout, out) = gix::prepare_clone(url, path)
    |  ________________________________________________-
159 | |                     .map_err(|err| {
160 | |                         format_err!(ErrorKind::Repo, "failed to prepare clone: {}", err)
161 | |                     })?
...   |
164 | |                     .configure_remote(|remote| Ok(remote.with_refspecs([REF_SPEC], DIR)?))
165 | |                     .fetch_then_checkout(&mut progress, should_interrupt)
    | |                     -^^^^^^^^^^^^^^^^^^^ method not found in `PrepareFetch`
    | |_____________________|
    | 
```

**Comment by CastilloDel** [comment]
I'm also experiencing the same error with `rustsec 0.29.1`

**Comment by Shnatsel** [comment]
It's another semver break in tame-index, I've reported the issue upstream: https://github.com/EmbarkStudios/tame-index/issues/55
