### ISSUE TITLE
Ghost Assigned by github-actions PRs

### ISSUE THREAD

**Issue by pinkforest** [rustsec/rustsec#630]
They appear when there is a PR that doesn't add advisories

e.g. when we bumped rustsec-admin 0.8.0 for rustdecimal
https://github.com/rustsec/advisory-db/pull/1308

Resulted into:
https://github.com/rustsec/advisory-db/pull/1309

Probably should adjust the workflow in db

**Comment by tarcieri** [comment]
It's a bug in the concurrency detector. We need a slightly smarter method, perhaps integrated into the ID assigner job

**Comment by Shnatsel** [comment]
I've opened a PR that should fix that: https://github.com/rustsec/advisory-db/pull/1332

**Comment by pinkforest** [comment]
I've used if:'s under job's to solve similar before:

https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution

You can do check-if job and then in assign-ids jobs you can match if: based on what happened in check-if

Further: Using contexts to access environment variable values
https://docs.github.com/en/actions/learn-github-actions/environment-variables

You can basically override the github environment file and do if from that -

Further: Passing values between steps and jobs in a workflow
you can use the value in subsequent steps of the same job by assigning the value to an existing or new environment variable and then writing this to the GITHUB_ENV environment file.

Also the job has to be dependency from another

**Comment by pinkforest** [comment]
FWIW - It's not fixed
The :ghost: is still with us after https://github.com/rustsec/advisory-db/pull/1332
https://github.com/rustsec/advisory-db/pull/1336

Also PRs typically run in the github action that is in the PR so it was already evident here it doesn't work:
https://github.com/rustsec/advisory-db/pull/1333

I can / will send a CI workflow that should eliminate this later based on above

**Comment by pinkforest** [comment]
The ghost :ghost: has not been annoying us :chains: for a while so yes it seemed to have disappeared indeed. Good stuff :partying_face:
